package com.haulmont.testtask.views.Main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
class MainViewDesign extends VerticalLayout {

    protected HorizontalLayout mainArea;

    protected CssLayout sideBar;

    protected VerticalLayout headerBar;

    NativeButton menuButton1;

    NativeButton menuButton2;

    Panel scrollPanel;

    MainViewDesign() {
        Design.read(this);
    }
}
