package com.haulmont.testtask.views.Group.windows;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.haulmont.testtask.views.Group.forms.GroupForm;
import com.vaadin.ui.NativeButton;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AddGroupWindowDesign extends VerticalLayout {

    protected GroupForm groupForm;

    protected NativeButton addOkButton;

    protected NativeButton addCancelButton;

    public AddGroupWindowDesign() {
        Design.read(this);
    }
}
