package com.haulmont.testtask.views.Student.windows;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DeleteStudentWindowDesign extends VerticalLayout {

    protected Label label;

    protected NativeButton deleteOkButton;

    protected NativeButton deleteCancelButton;

    public DeleteStudentWindowDesign() {
        Design.read(this);
    }
}
