package com.haulmont.testtask.views.Group;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GroupViewDesign extends VerticalLayout {

    protected NativeButton addNewButton;

    protected NativeButton editButton;

    protected NativeButton deleteButton;

    protected Grid grid;

    public GroupViewDesign() {
        Design.read(this);
    }
}
